### ISSUE TITLE
npm install error - can't find python?

### ISSUE THREAD

**Issue by hublerdesignworks** [cncjs/cncjs-pendant-keyboard#3]
Please help...

Duane@DESKTOP-TCI8GAO MINGW64 ~/documents/github/cncjs-pendant-keyboard (master)
$ npm install

> node-hid@0.5.7 install C:\Users\huble\documents\github\cncjs-pendant-keyboard\node_modules\node-hid
> prebuild-install || node-gyp rebuild

prebuild-install info begin Prebuild-install version 2.5.1
prebuild-install info looking for local prebuild @ prebuilds\node-hid-v0.5.7-node-v59-win32-x64.tar.gz
prebuild-install info looking for cached prebuild @ C:\Users\huble\AppData\Roaming\npm-cache\_prebuilds\https-github.com-node-hid-node-hid-releases-download-v0.5.7-node-hid-v0.5.7-node-v59-win32-x64.tar.gz
prebuild-install http request GET https://github.com/node-hid/node-hid/releases/download/v0.5.7/node-hid-v0.5.7-node-v59-win32-x64.tar.gz
prebuild-install http 404 https://github.com/node-hid/node-hid/releases/download/v0.5.7/node-hid-v0.5.7-node-v59-win32-x64.tar.gz
prebuild-install WARN install No prebuilt binaries found (target=9.5.0 runtime=node arch=x64 platform=win32)

C:\Users\huble\documents\github\cncjs-pendant-keyboard\node_modules\node-hid>if not defined npm_config_node_gyp (node "C:\Program Files\nodejs\node_modules\npm\node_modules\npm-lifecycle\node-gyp-bin\\..\..\node_modules\node-gyp\bin\node-gyp.js" rebuild )  else (node "C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\bin\node-gyp.js" rebuild )
gyp ERR! configure error
gyp ERR! stack Error: Can't find Python executable "python", you can set the PYTHON env variable.
gyp ERR! stack     at PythonFinder.failNoPython (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:483:19)
gyp ERR! stack     at PythonFinder.<anonymous> (C:\Program Files\nodejs\node_modules\npm\node_modules\node-gyp\lib\configure.js:508:16)
gyp ERR! stack     at C:\Program Files\nodejs\node_modules\npm\node_modules\graceful-fs\polyfills.js:284:29
gyp ERR! stack     at FSReqWrap.oncomplete (fs.js:166:21)
gyp ERR! System Windows_NT 10.0.16299
gyp ERR! command "C:\\Program Files\\nodejs\\node.exe" "C:\\Program Files\\nodejs\\node_modules\\npm\\node_modules\\node-gyp\\bin\\node-gyp.js" "rebuild"
gyp ERR! cwd C:\Users\huble\documents\github\cncjs-pendant-keyboard\node_modules\node-hid
gyp ERR! node -v v9.5.0
gyp ERR! node-gyp -v v3.6.2
gyp ERR! not ok
npm ERR! code ELIFECYCLE
npm ERR! errno 1
npm ERR! node-hid@0.5.7 install: `prebuild-install || node-gyp rebuild`
npm ERR! Exit status 1
npm ERR!
npm ERR! Failed at the node-hid@0.5.7 install script.
npm ERR! This is probably not a problem with npm. There is likely additional logging output above.

npm ERR! A complete log of this run can be found in:
npm ERR!     C:\Users\huble\AppData\Roaming\npm-cache\_logs\2018-02-19T02_06_53_160Z-debug.log

**Comment by nsfilho** [comment]
@hublerdesignworks this kind of error sometimes appears no make sense :) -- but node-gyp (dependency) it's a really "strange" library. I'll review all dependencies from this project.
